---
- hosts: srv
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: restart nginx
      service:
        name: nginx
        state: started
